### PR TITLE
Don't leak the injector instance into the class.

### PR DESCRIPTION
**Pull request by groner**
I noticed this while scratching my `Injector.alias()` itch (#13).

### CODE REVIEW

**Comment by groner** [comment]
Prior to this change, `Injector.sub()` instances would provide an `'injector'` service if one had been created by instantiating `Injector` or one of it's bases with `provide_self=True`.  This was the wrong injector, but if it wasn't closed, code may have executed using the other injector without breaking.  Now `Injector.sub()` instances will have no injector, because `Injector.sub()` uses it's arguments to customize the subinjector.

We need another way to allow access to the injector in this case.  Here are some ideas:
1. Revise the `Injector.sub()` API to allow `provide_self` to be specified in some way (maybe just a reserved kwarg).
2. Allow the `provide_self` bit to be configured on the injector class.
3. Stop pretending we can provide a sandbox in python and provide the injector always.

My preference is for 3.  It might seem radical, but I really don't think it is.

**Comment by rduplain** [comment]
Thanks for this. We can go with 3 given how subinjectors work.

**Comment by groner** [comment]
I'll come up with a patch.

**Comment by groner** [comment]
I see the docs need to be updated.  I'm working on that now.

**Comment by groner** [comment]
So now we don't support `provide_self=False` with subinjectors.  Should we just deprecate `provide_self=False`?

**Comment by rduplain** [comment]
Yes.

**Comment by groner** [comment]
I've merely omitted any discussion of `Injector(provide_self=False)` in the Injector docstring.

Should we document the deprecation or add something like this?
```python
    if not provide_self:
        warnings.warn(DeprecationWarning('provide_self=False is not supported'))
```

**Comment by rduplain** [comment]
`DeprecationWarning` should be enough.

**Pull request merged**
