### PR TITLE
Maintain a list of finalizers to call on injector close.

### PR DESCRIPTION
**Pull request by groner**

### CODE REVIEW

**Comment by rduplain** [comment]
This change will cause all Providers to get close called even when nothing happened, such that they will need to know whether anything needs to be done. Not that there are many users of jeni or anything, but it's good semver practice to bump to 0.4.0 when merged.

**Comment by rduplain** [comment]
I like where this is going, where an Injector instance will have a list of close callback functions that can come from anywhere. Use cases are helpful when you have them.

**Comment by groner** [comment]
In our project at MN we have a DecoratingInjector that allows decoration and configuration of services.  Decorations of a service are applied when that service is instantiated.

Here's an example:
```python
@Injector.configure('sendmail')
def hookup_sendmail_log(sendmail, request_id: 'request-id'):
    @sendmail.onsend
    def record_message(message):
        with open('maillog-'+request_id, 'a') as logfh:
            logfh.write(message)
```

Now, I'd like to summarize the messages sent during a request in the main application log.  I don't want to use an after-request handler, because I want the summary to be provided when scripts run.  If I were modifying the sendmail service, I would do this in the close call.  Currently, there's no way for DecoratingInjector to augment the closing phase of the service in order to provide an equivalent mechanism for decorators.

With this change, the DecoratingInjector would be able to collect finalizers as each decorator is applied.

**Comment by groner** [comment]
I've done a rough import of DecoratingInjector here. groner@41b283c9d421e7c70eea78ca543c5c01a47ac740

**Comment by rduplain** [comment]
I'm +1 to merging this.

**Pull request merged**
